using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Zylance.SourceGenerators.Models;

namespace Zylance.SourceGenerators.Generators;

internal static class AssemblyRegistrationCodeGenerator
{
    public static void Execute(
        ImmutableArray<ControllerInfo?> controllers,
        SourceProductionContext context
    )
    {
        var validControllers = controllers.Where(c => c != null).Cast<ControllerInfo>().ToList();

        if (validControllers.Count == 0)
            return;

        var source = Generate(validControllers);
        context.AddSource("ControllerRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Generate(List<ControllerInfo> controllers)
    {
        var primaryNamespace = controllers
            .GroupBy(c => c.Namespace)
            .OrderByDescending(g => g.Count())
            .First()
            .Key;

        Console.WriteLine("[Zylance] Generating ControllerRegistration.cs");
        Console.WriteLine("[Zylance] Namespace: " + primaryNamespace);

        var model = new TemplateModel
        {
            Namespace = primaryNamespace,
            Controllers = controllers.OrderBy(c => c.ClassName).Select(c => new TemplateControllerModel
            {
                ClassName = c.ClassName,
                FullTypeName = c.FullTypeName,
                CamelCaseName = ToCamelCase(c.ClassName),
            }).ToList(),
        };

        return Template(model);
    }

    private static string ToCamelCase(string str)
    {
        if (string.IsNullOrEmpty(str) || char.IsLower(str[0]))
            return str;

        return char.ToLowerInvariant(str[0]) + str.Substring(1);
    }

    private static string Template(TemplateModel data)
    {
        var sb = new StringBuilder();
        sb.Append(
            //language=csharp
            $$"""
              // <auto-generated/>
              #nullable enable

              using System;
              using Microsoft.Extensions.DependencyInjection;
              using Microsoft.Extensions.DependencyInjection.Extensions;
              using Zylance.Core.Controllers;
              using Zylance.Core.Controllers.Services;

              namespace Zylance.Core.Extensions;

              public static class ControllerRegistration
              {
                  internal static IServiceCollection AddZylanceRouter(this IServiceCollection services)
                  {
                      {{string.Join("\n", data.Controllers.Select(controller =>
                          //language=csharp
                          $"services.TryAddSingleton<{controller.ClassName}>();"
                      ))}}

                      services.TryAddSingleton<RouterService>(sp =>
                      {
                          var router = new RouterService();

                          {{string.Join("\n", data.Controllers.Select(controller =>
                              //language=csharp
                              $"""
                               var {controller.CamelCaseName} = sp.GetRequiredService<{controller.ClassName}>();
                               router.Register{controller.ClassName}({controller.CamelCaseName});
                               """
                          ))}}

                          return router;
                      });

                      return services;
                  }
              }
              """
        );
        return sb.ToString();
    }

    private class TemplateModel
    {
        public required string Namespace { get; init; }
        public required List<TemplateControllerModel> Controllers { get; init; }
    }

    private class TemplateControllerModel
    {
        public required string ClassName { get; init; }
        public required string FullTypeName { get; init; }
        public required string CamelCaseName { get; init; }
    }
}
