using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Zylance.SourceGenerators.Models;
using static Zylance.SourceGenerators.Utils.TemplateUtils;

namespace Zylance.SourceGenerators.Generators;

internal static class ControllerRegistrationCodeGenerator
{
    public static void Execute(
        ImmutableArray<ControllerInfo> controllers,
        SourceProductionContext context
    )
    {
        var source = Generate(controllers.ToList());
        context.AddSource("ControllerRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Generate(List<ControllerInfo> controllers)
    {
        var namespaces = controllers
            .SelectMany(controller => controller.Namespaces)
            .Distinct(SymbolEqualityComparer.Default)
            .Where(s => s is not null)
            .Select(s => s!)
            .ToList();

        //language=csharp
        return $$"""
                 // <auto-generated/>
                 #nullable enable

                 using System;
                 using Microsoft.Extensions.DependencyInjection;
                 using Microsoft.Extensions.DependencyInjection.Extensions;
                 using Zylance.Core.Lib.Gateway.Services;
                 {{ForEach(namespaces, ns => $"using {ns.ToDisplayString()};")}}

                 namespace Zylance.Core.Lib.Gateway.Extensions;

                 public static class ControllerRegistration
                 {
                     internal static IServiceCollection AddZylanceRouter(this IServiceCollection services)
                     {
                         {{ForEach(controllers, c => $"services.TryAddSingleton<{c.ClassType.Name}>();")}}

                         services.TryAddSingleton<RouterService>(sp =>
                         {
                             var router = new RouterService();

                             {{ForEach(controllers, c => $"router.Register{c.ClassType.Name}(sp.GetRequiredService<{c.ClassType.Name}>());")}}

                             return router;
                         });

                         return services;
                     }
                 }
                 """;
    }
}
