using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Zylance.SourceGenerators.Models;
using static Zylance.SourceGenerators.Utils.TemplateUtils;

namespace Zylance.SourceGenerators.Generators;

internal static class RouterServiceExtensionsCodeGenerator
{
    public static void Execute(ControllerInfo controller, SourceProductionContext context)
    {
        // Only generate code if there are handlers
        if (controller.HandlerCount == 0)
            return;

        var source = Generate(controller);
        context.AddSource($"{controller.ClassType.Name}_Registration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Generate(ControllerInfo controller)
    {
        var requestHandlers = controller.RequestHandlers;
        var eventHandlers = controller.EventHandlers;
        var namespaces = controller.Namespaces;
        var controllerClassName = controller.ClassType.Name;

        var validRequestHandlers = requestHandlers
            .Where(h => h.IsValid)
            .Select(h => h.ToValid())
            .ToList();

        var validEventHandlers = eventHandlers
            .Where(h => h.IsValid)
            .Select(h => h.ToValid())
            .ToList();

        //language=csharp
        return $$"""
                 // <auto-generated/>
                 #nullable enable

                 using System;
                 using System.Threading.Tasks;
                 using Zylance.Core.Controllers.Services;
                 using Zylance.Core.Controllers.Utils;
                 {{ForEach(namespaces, ns => $"using {ns.ToDisplayString()};")}}

                 namespace Zylance.Core.Extensions;

                 public static partial class RouterServiceExtensions
                 {
                     public static RouterService Register{{controllerClassName}}(this RouterService router, {{controllerClassName}} controller)
                     {
                         {{ForEach(validRequestHandlers, handler =>
                             //language=csharp
                             $$"""
                               {
                                   var reqAction = ProtoActionUtils.GetAction<{{handler.RequestType.Name}}>();
                                   var resAction = ProtoActionUtils.GetAction<{{handler.ResponseType.Name}}>();

                                   if (string.IsNullOrEmpty(reqAction))
                                       throw new InvalidOperationException(
                                           "Cannot auto-detect action for method {{handler.Method.Name}}: " +
                                           "Request type {{handler.RequestType}} is missing the (action) option in its .proto definition."
                                       );

                                   if (string.IsNullOrEmpty(resAction))
                                       throw new InvalidOperationException(
                                           "Cannot auto-detect action for method {{handler.Method.Name}}: " +
                                           "Response type {{handler.ResponseType}} is missing the (action) option in its .proto definition."
                                       );

                                   if (reqAction != resAction)
                                       throw new InvalidOperationException(
                                           "Action mismatch for method {{handler.Method.Name}}: " +
                                           $"Request type has action '{reqAction}' but Response type has action '{resAction}'.");

                                   var action = reqAction;
                                   Console.WriteLine($"[RouterService] Registering request handler '{action}': {{controller.ClassType.Name}}.{{handler.Method.Name}}");

                                   {{(
                                       handler.IsAsync
                                           ? $"router.Use(action, RequestHandlerUtils.Wrap<{handler.RequestType.Name}, {handler.ResponseType.Name}>(controller.{handler.Method.Name}));"
                                           : $"router.Use(action, RequestHandlerUtils.WrapSync<{handler.RequestType.Name}, {handler.ResponseType.Name}>(controller.{handler.Method.Name}));"
                                   )}}
                               }
                               """
                         )}}

                         {{ForEach(validEventHandlers, handler =>
                             //language=csharp
                             $$"""
                               {
                                   var eventName = ProtoActionUtils.GetEventName<{{handler.EventType.Name}}>();

                                   if (string.IsNullOrEmpty(eventName))
                                       throw new InvalidOperationException(
                                           "Cannot auto-detect eventName for method {{handler.Method.Name}}: " +
                                           "Event type {{handler.EventType.Name}} is missing the (eventName) option in its .proto definition.");

                                   Console.WriteLine($"[RouterService] Registering event handler '{eventName}': {{controller.ClassType.Name}}.{{handler.Method.Name}}");

                                   {{(
                                       handler.IsAsync
                                           ? $"router.Use(eventName, EventHandlerUtils.Wrap<{handler.EventType.Name}>(controller.{handler.Method.Name}));"
                                           : $"router.Use(eventName, EventHandlerUtils.WrapSync<{handler.EventType.Name}>(controller.{handler.Method.Name}));"
                                   )}}
                               }
                               """
                         )}}

                         return router;
                     }
                 }
                 """;
    }
}
