using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Zylance.SourceGenerators.Models;

namespace Zylance.SourceGenerators.Generators;

internal static class RouterServiceExtensionsCodeGenerator
{
    public static void Execute(ControllerInfo controller, SourceProductionContext context)
    {
        // Report any diagnostics
        foreach (var diagnostic in controller.Diagnostics)
            context.ReportDiagnostic(diagnostic);

        // Only generate code if there are handlers
        if (controller.Handlers.Count <= 0)
            return;

        var source = Generate(controller);
        context.AddSource($"{controller.ClassName}_Registration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Generate(ControllerInfo controller)
    {
        var model = new TemplateModel
        {
            Namespace = controller.Namespace,
            ClassName = controller.ClassName,
            FullTypeName = controller.FullTypeName,
            Handlers = controller.Handlers.Select(h => new TemplateHandlerModel
            {
                Type = h.Type.ToString(),
                MethodName = h.MethodName,
                Action = h.Action,
                RequestType = h.RequestTypeName,
                ResponseType = h.ResponseTypeName,
                EventType = h.EventTypeName,
                IsAsync = h.IsAsync,
            }).ToList(),
        };

        return Template(model);
    }

    private static string Template(TemplateModel data)
    {
        var requestHandlers = data.Handlers.FindAll(handler => handler.Type == "Request");
        var eventHandlers = data.Handlers.FindAll(handler => handler.Type == "Event");

        var sb = new StringBuilder();
        sb.Append(
            //language=csharp
            $$"""
              // <auto-generated/>
              #nullable enable

              using System;
              using System.Threading.Tasks;
              using Zylance.Core.Controllers;
              using Zylance.Core.Controllers.Services;
              using Zylance.Core.Controllers.Utils;
              using Zylance.Core.Utils;
              using Zylance.Contract.Api.Echo;
              using Zylance.Contract.Api.File;
              using Zylance.Contract.Api.Status;
              using Zylance.Contract.Api.Vault;

              namespace Zylance.Core.Extensions;

              public static partial class RouterServiceExtensions
              {
                  public static RouterService Register{{data.ClassName}}(this RouterService router, {{data.ClassName}} controller)
                  {
                      {{string.Join("\n        ", requestHandlers.Select(handler => {
                          var requestSb = new StringBuilder();

                          requestSb.AppendLine("{");
                          requestSb.AppendLine(
                              handler.Action is not null
                                  //language=csharp
                                  ? $"""
                                     var action = "{handler.Action}";
                                     """
                                  //language=csharp
                                  : $$"""
                                      var reqAction = ProtoActionUtils.GetAction<{{handler.RequestType}}>();
                                      var resAction = ProtoActionUtils.GetAction<{{handler.ResponseType}}>();
                                                        
                                      if (string.IsNullOrEmpty(reqAction))
                                          throw new InvalidOperationException(
                                              "Cannot auto-detect action for method {{handler.MethodName}}: " + 
                                              "Request type {{handler.RequestType}} is missing the (action) option in its .proto definition." 
                                          );
                                                        
                                      if (string.IsNullOrEmpty(resAction))
                                          throw new InvalidOperationException(
                                              "Cannot auto-detect action for method {{handler.MethodName}}: " +
                                              "Response type {{handler.ResponseType}} is missing the (action) option in its .proto definition." 
                                           );
                                                        
                                      if (reqAction != resAction)
                                          throw new InvalidOperationException(
                                              "Action mismatch for method {{handler.MethodName}}: " +
                                              $"Request type has action '{reqAction}' but Response type has action '{resAction}'.");
                                                        
                                      var action = reqAction;
                                      """
                          );

                          requestSb.AppendLine(
                              //language=csharp
                              $$"""
                                Console.WriteLine($"[RouterService] Registering request handler '{action}': {{data.ClassName}}.{{handler.MethodName}}");
                                """
                          );

                          requestSb.AppendLine(
                              handler.IsAsync
                                  ? $"router.Use(action, RequestHandlerUtils.Wrap<{handler.RequestType}, {handler.ResponseType}>(controller.{handler.MethodName}));"
                                  : $"router.Use(action, RequestHandlerUtils.WrapSync<{handler.RequestType}, {handler.ResponseType}>(controller.{handler.MethodName}));"
                          );

                          requestSb.AppendLine("}");
                          return requestSb.ToString();
                      }))}}
                         

                      {{string.Join("\n", eventHandlers.Select(handler => {
                          var eventSb = new StringBuilder();

                          eventSb.AppendLine("{");
                          eventSb.AppendLine(
                              handler.Action is not null
                                  //language=csharp
                                  ? $"""
                                     var eventName = "{handler.Action}";
                                     """
                                  //language=csharp
                                  : $"""
                                     var eventName = ProtoActionUtils.GetEventName<{handler.EventType}>();

                                     if (string.IsNullOrEmpty(eventName))
                                         throw new InvalidOperationException(
                                             "Cannot auto-detect eventName for method {handler.MethodName}: " +
                                             "Event type {handler.EventType} is missing the (eventName) option in its .proto definition.");
                                     """
                          );

                          eventSb.AppendLine(
                              //language=csharp
                              $$"""
                                Console.WriteLine($"[RouterService] Registering event handler '{eventName}': {{data.ClassName}}.{{handler.MethodName}}");
                                """
                          );

                          eventSb.AppendLine(
                              handler.IsAsync
                                  ? $"router.Use(eventName, EventHandlerUtils.Wrap<{handler.EventType}>(controller.{handler.MethodName}));"
                                  : $"router.Use(eventName, EventHandlerUtils.WrapSync<{handler.EventType}>(controller.{handler.MethodName}));"
                          );

                          eventSb.AppendLine("}");
                          return eventSb.ToString();
                      }))}}
                      
                      return router;
                  }
              }
              """
        );
        return sb.ToString();
    }

    private class TemplateModel
    {
        public required string Namespace { get; init; }
        public required string ClassName { get; init; }
        public required string FullTypeName { get; init; }
        public required List<TemplateHandlerModel> Handlers { get; init; }
    }

    private class TemplateHandlerModel
    {
        public required string Type { get; init; }
        public required string MethodName { get; init; }
        public string? Action { get; init; }
        public string? RequestType { get; init; }
        public string? ResponseType { get; init; }
        public string? EventType { get; init; }
        public required bool IsAsync { get; init; }
    }
}
