syntax = "proto3";
package zylance.contract;

import "zylance/extensions/Zylance.proto";

option csharp_namespace = "Zylance.Contract.Api.Settings";

// === Models ===
message UserPreferencesData {
  DateTimeFormatData dateTimeFormat = 1;
}

message DateTimeOptionsData {
  repeated string datePatterns = 1;
  repeated string timePatterns = 2;
}

message DateTimeFormatData {
  bool dateFollowSystem = 1; // if true, datePattern is the same as system settings
  string datePattern = 2;

  bool timeFollowSystem = 3; // if true, timePattern is the same as system settings
  string timePattern = 4;
}

// === Actions ===
message GetUserPreferencesReq {
  option (action) = "Settings:GetUserPreferences";
}

message GetUserPreferencesRes {
  option (action) = "Settings:GetUserPreferences";
  UserPreferencesData preferences = 1;
}

message SetUserPreferencesReq {
  option (action) = "Settings:SetUserPreferences";
  UserPreferencesData preferences = 1;
}

message SetUserPreferencesRes {
  option (action) = "Settings:SetUserPreferences";
  UserPreferencesData preferences = 1;
}

message GetDateTimeOptionsReq {
  option (action) = "Settings:GetDateTimeOptions";
}

message GetDateTimeOptionsRes {
  option (action) = "Settings:GetDateTimeOptions";
  DateTimeOptionsData options = 1;
}
