syntax = "proto3";
package zylance.contract;

import "zylance/extensions/Zylance.proto";
import "zylance/models/Vault.proto";

option csharp_namespace = "Zylance.Contract.Api.Vault";

// === Vault Operation Messages ===
message VaultOpenReq {
  option (action) = "Vault:OpenVault";
}

message VaultOpenRes {
  option (action) = "Vault:OpenVault";
  VaultRef vault_ref = 1;
}

message VaultCreateReq {
  option (action) = "Vault:CreateVault";
}

message VaultCreateRes {
  option (action) = "Vault:CreateVault";
  VaultRef vault_ref = 1;
}

message VaultCloseReq {
  option (action) = "Vault:CloseVault";
}

message VaultCloseRes {
  option (action) = "Vault:CloseVault";
}

message VaultOpenedEvt {
  option (eventName) = "Vault:VaultOpened";
  VaultRef vault_ref = 1;
}

message VaultClosedEvt {
  option (eventName) = "Vault:VaultClosed";
}

message VaultUnlockedEvt {
  option (eventName) = "Vault:Unlocked";
  VaultRef vault_ref = 1;
}

message VaultLockedEvt {
  option (eventName) = "Vault:Locked";
  VaultRef vault_ref = 1;
}

message VaultGetStatusReq {
  option (action) = "Vault:GetStatus";
}

message VaultGetStatusRes {
  option (action) = "Vault:GetStatus";
  optional VaultRef vault_ref = 1;
}

