#!/usr/bin/env node

/**
 * Generates type-safe action and event name constants from Protocol Buffer definitions.
 * 
 * This script parses all .proto files to extract:
 * - Actions (from `option (action) = "..."`)
 * - Events (from `option (eventName) = "..."`)
 * 
 * It then generates:
 * - TypeScript: Type-safe string literal union types and constants
 * - C#: Static class with string constants
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { glob } from "glob";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const CONTRACT_DIR = join(SCRIPT_DIR, "..");
const PROTO_DIR = join(CONTRACT_DIR, "zylance");

interface ActionOrEvent {
  name: string;
  type: "action" | "event";
  file: string;
}

/**
 * Parse a proto file and extract all action and event names.
 */
function parseProtoFile(filePath: string): ActionOrEvent[] {
  const content = readFileSync(filePath, "utf-8");
  const results: ActionOrEvent[] = [];
  
  // Match option (action|eventName) = "value" lines
  const optionPattern = /option\s*\((action|eventName)\)\s*=\s*['"]([^'"]+)['"]/g;
  
  let match: RegExpExecArray | null;
  while ((match = optionPattern.exec(content)) !== null) {
    const [, optionType, value] = match;
    results.push({
      name: value,
      type: optionType === "action" ? "action" : "event",
      file: relative(CONTRACT_DIR, filePath),
    });
  }
  
  return results;
}

/**
 * Find all .proto files in the api directory.
 */
async function findProtoFiles(): Promise<string[]> {
  const pattern = join(PROTO_DIR, "api", "**", "*.proto");
  return await glob(pattern);
}

/**
 * Generate TypeScript constants file.
 */
function generateTypeScript(actions: ActionOrEvent[], events: ActionOrEvent[]): string {
  const allActions = [...new Set(actions.map(a => a.name))].sort();
  const allEvents = [...new Set(events.map(e => e.name))].sort();
  
  const actionTypes = allActions.map(name => `  | "${name}"`).join("\n");
  const eventTypes = allEvents.map(name => `  | "${name}"`).join("\n");
  
  const actionConstants = allActions
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_");
      return `  ${safeName}: "${name}" as const,`;
    })
    .join("\n");
    
  const eventConstants = allEvents
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_");
      return `  ${safeName}: "${name}" as const,`;
    })
    .join("\n");
  
  return `/**
 * Auto-generated type-safe action and event name constants.
 * DO NOT EDIT - Generated by Scripts/generate-constants.ts
 */

/**
 * All available request action names.
 */
export type ZylanceAction =
${actionTypes};

/**
 * All available event names.
 */
export type ZylanceEvent =
${eventTypes};

/**
 * Type-safe action name constants.
 */
export const ZylanceActions = {
${actionConstants}
} as const;

/**
 * Type-safe event name constants.
 */
export const ZylanceEvents = {
${eventConstants}
} as const;
`;
}

/**
 * Generate C# constants file.
 */
function generateCSharp(actions: ActionOrEvent[], events: ActionOrEvent[]): string {
  const allActions = [...new Set(actions.map(a => a.name))].sort();
  const allEvents = [...new Set(events.map(e => e.name))].sort();
  
  const actionConstants = allActions
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_");
      return `        public const string ${safeName} = "${name}";`;
    })
    .join("\n");
    
  const eventConstants = allEvents
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_");
      return `        public const string ${safeName} = "${name}";`;
    })
    .join("\n");
  
  return `// <auto-generated>
//     This file is auto-generated by Scripts/generate-constants.ts
//     DO NOT EDIT - Changes will be overwritten
// </auto-generated>

namespace Zylance.Contract;

/// <summary>
/// Type-safe action and event name constants extracted from Protocol Buffer definitions.
/// </summary>
public static class ZylanceConstants
{
    /// <summary>
    /// All available request action names.
    /// </summary>
    public static class Actions
    {
${actionConstants}
    }

    /// <summary>
    /// All available event names.
    /// </summary>
    public static class Events
    {
${eventConstants}
    }
}
`;
}

/**
 * Main function to generate type-safe constants.
 */
export async function generateConstants(tsOutputDir?: string): Promise<void> {
  console.log("Scanning proto files...");
  const protoFiles = await findProtoFiles();
  console.log(`Found ${protoFiles.length} proto file(s)`);
  
  const allItems: ActionOrEvent[] = [];
  for (const file of protoFiles) {
    const items = parseProtoFile(file);
    allItems.push(...items);
    if (items.length > 0) {
      console.log(`  ${relative(CONTRACT_DIR, file)}: ${items.length} item(s)`);
    }
  }
  
  const actions = allItems.filter(item => item.type === "action");
  const events = allItems.filter(item => item.type === "event");
  
  console.log(`\nExtracted ${actions.length} actions and ${events.length} events`);
  
  const tsContent = generateTypeScript(actions, events);
  const csContent = generateCSharp(actions, events);
  
  // Generate TypeScript in Contract/Generated for reference
  const tsContractPath = join(CONTRACT_DIR, "Generated", "ZylanceConstants.ts");
  writeFileSync(tsContractPath, tsContent, "utf-8");
  console.log(`\nGenerated TypeScript: ${relative(CONTRACT_DIR, tsContractPath)}`);
  
  // Also generate in the UI project if output directory is specified
  if (tsOutputDir) {
    const tsOutputPath = join(tsOutputDir, "ZylanceConstants.ts");
    writeFileSync(tsOutputPath, tsContent, "utf-8");
    console.log(`Generated TypeScript: ${relative(CONTRACT_DIR, tsOutputPath)}`);
  }
  
  // Generate C#
  const csOutputPath = join(CONTRACT_DIR, "Generated", "ZylanceConstants.cs");
  writeFileSync(csOutputPath, csContent, "utf-8");
  console.log(`Generated C#: ${relative(CONTRACT_DIR, csOutputPath)}`);
  
  console.log("\n✓ Successfully generated type-safe constants!");
}

// Run if this file is executed directly
const isMainModule = fileURLToPath(import.meta.url) === process.argv[1];
if (isMainModule) {
  generateConstants().catch(error => {
    console.error("Error:", error);
    process.exit(1);
  });
}
