/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './Routes/__root'
import { Route as VaultRouteRouteImport } from './Routes/vault/route'
import { Route as VaultIndexRouteImport } from './Routes/vault/index'
import { Route as LockedIndexRouteImport } from './Routes/locked/index'
import { Route as LockedUnlockVaultRouteImport } from './Routes/locked/unlock-vault'
import { Route as LockedSelectVaultRouteImport } from './Routes/locked/select-vault'
import { Route as VaultLedgerIndexRouteImport } from './Routes/vault/ledger/index'
import { Route as VaultNotesIndexRouteImport } from './Routes/vault/notes/index'

const VaultRouteRoute = VaultRouteRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const LockedIndexRoute = LockedIndexRouteImport.update({
  id: '/locked/',
  path: '/locked/',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedUnlockVaultRoute = LockedUnlockVaultRouteImport.update({
  id: '/locked/unlock-vault',
  path: '/locked/unlock-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedSelectVaultRoute = LockedSelectVaultRouteImport.update({
  id: '/locked/select-vault',
  path: '/locked/select-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultLedgerIndexRoute = VaultLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultNotesIndexRoute = VaultNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => VaultRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/vault': typeof VaultRouteRouteWithChildren
  '/locked/select-vault': typeof LockedSelectVaultRoute
  '/locked/unlock-vault': typeof LockedUnlockVaultRoute
  '/locked/': typeof LockedIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/ledger/': typeof VaultLedgerIndexRoute
  '/vault/notes/': typeof VaultNotesIndexRoute
}
export interface FileRoutesByTo {
  '/locked/select-vault': typeof LockedSelectVaultRoute
  '/locked/unlock-vault': typeof LockedUnlockVaultRoute
  '/locked': typeof LockedIndexRoute
  '/vault': typeof VaultIndexRoute
  '/vault/ledger': typeof VaultLedgerIndexRoute
  '/vault/notes': typeof VaultNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/vault': typeof VaultRouteRouteWithChildren
  '/locked/select-vault': typeof LockedSelectVaultRoute
  '/locked/unlock-vault': typeof LockedUnlockVaultRoute
  '/locked/': typeof LockedIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/ledger/': typeof VaultLedgerIndexRoute
  '/vault/notes/': typeof VaultNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/vault'
    | '/locked/select-vault'
    | '/locked/unlock-vault'
    | '/locked/'
    | '/vault/'
    | '/vault/ledger/'
    | '/vault/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/locked/select-vault'
    | '/locked/unlock-vault'
    | '/locked'
    | '/vault'
    | '/vault/ledger'
    | '/vault/notes'
  id:
    | '__root__'
    | '/vault'
    | '/locked/select-vault'
    | '/locked/unlock-vault'
    | '/locked/'
    | '/vault/'
    | '/vault/ledger/'
    | '/vault/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VaultRouteRoute: typeof VaultRouteRouteWithChildren
  LockedSelectVaultRoute: typeof LockedSelectVaultRoute
  LockedUnlockVaultRoute: typeof LockedUnlockVaultRoute
  LockedIndexRoute: typeof LockedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/locked/': {
      id: '/locked/'
      path: '/locked'
      fullPath: '/locked/'
      preLoaderRoute: typeof LockedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked/unlock-vault': {
      id: '/locked/unlock-vault'
      path: '/locked/unlock-vault'
      fullPath: '/locked/unlock-vault'
      preLoaderRoute: typeof LockedUnlockVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked/select-vault': {
      id: '/locked/select-vault'
      path: '/locked/select-vault'
      fullPath: '/locked/select-vault'
      preLoaderRoute: typeof LockedSelectVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/ledger/': {
      id: '/vault/ledger/'
      path: '/ledger'
      fullPath: '/vault/ledger/'
      preLoaderRoute: typeof VaultLedgerIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/notes/': {
      id: '/vault/notes/'
      path: '/notes'
      fullPath: '/vault/notes/'
      preLoaderRoute: typeof VaultNotesIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
  }
}

interface VaultRouteRouteChildren {
  VaultIndexRoute: typeof VaultIndexRoute
  VaultLedgerIndexRoute: typeof VaultLedgerIndexRoute
  VaultNotesIndexRoute: typeof VaultNotesIndexRoute
}

const VaultRouteRouteChildren: VaultRouteRouteChildren = {
  VaultIndexRoute: VaultIndexRoute,
  VaultLedgerIndexRoute: VaultLedgerIndexRoute,
  VaultNotesIndexRoute: VaultNotesIndexRoute,
}

const VaultRouteRouteWithChildren = VaultRouteRoute._addFileChildren(
  VaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  VaultRouteRoute: VaultRouteRouteWithChildren,
  LockedSelectVaultRoute: LockedSelectVaultRoute,
  LockedUnlockVaultRoute: LockedUnlockVaultRoute,
  LockedIndexRoute: LockedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
