using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Zylance.SourceGenerators.Models;
using static Zylance.SourceGenerators.Utils.TemplateUtils;

namespace Zylance.SourceGenerators.Generators;

internal static class AddZylanceRouterCodeGenerator
{
    public static void Execute(ImmutableArray<ControllerInfo> controllers, SourceProductionContext context)
    {
        var source = Generate(controllers.ToList());
        context.AddSource("ControllerRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string Generate(List<ControllerInfo> controllers)
    {
        var namespaces = controllers
            .Select(c => c.Namespace)
            .Where(ns => !ns.IsGlobalNamespace)
            .Distinct(SymbolEqualityComparer.Default)
            .OfType<INamespaceSymbol>()
            .ToList();

        //language=csharp
        return $$"""
                 // <auto-generated/>
                 #nullable enable

                 using System;
                 using Microsoft.Extensions.DependencyInjection;
                 using Microsoft.Extensions.DependencyInjection.Extensions;
                 using Zylance.Core.Router.Services;
                 {{ForEach(namespaces, ns => $"using {ns.ToDisplayString()};")}}

                 namespace Zylance.Core.Lib.Gateway.Extensions;

                  /// <summary>
                  /// Registers generated controllers and the RouterService into the dependency injection container.
                  /// </summary>
                  public static class ControllerRegistration
                 {
                     internal static IServiceCollection AddZylanceRouter(this IServiceCollection services)
                     {
                         {{ForEach(controllers, c => $"services.TryAddSingleton<{c.ClassType.Name}>();")}}

                         services.TryAddSingleton<RouterService>(sp =>
                         {
                             var router = new RouterService();

                             {{ForEach(
                                 controllers,
                                 c => $"router.Register{c.ClassType.Name}(sp.GetRequiredService<{c.ClassType.Name}>());"
                             )}}

                             return router;
                         });

                         return services;
                     }
                 }
                 """;
    }
}
