/**
 * Generates type-safe action and event name constants from Protocol Buffer definitions.
 *
 * This script parses all .proto files to extract:
 * - Actions (from `option (action) = "..."`)
 * - Events (from `option (eventName) = "..."`)
 *
 * It then generates:
 * - TypeScript: Type-safe string literal union types and constants
 * - C#: Static class with string constants
 */

import * as fs from "node:fs"
import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { glob } from "glob"
import { DEST_DIR } from "./paths"

const SCRIPT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const CONTRACT_DIR = path.resolve(SCRIPT_DIR, "..")

interface ActionOrEvent {
  name: string;
  type: "action" | "event";
  file: string;
}

/**
 * Main function to generate type-safe constants.
 */
export async function generateConstants (): Promise<void> {
  console.log("\nGenerating type-safe action and event constants...")

  console.log("Scanning proto files...")
  const protoFiles = await findProtoFiles()
  console.log(`Found ${protoFiles.length} proto file(s)`)

  const allItems: ActionOrEvent[] = []
  for (const file of protoFiles) {
    const items = parseProtoFile(file)
    allItems.push(...items)
    if (items.length > 0) {
      console.log(`  ${path.relative(CONTRACT_DIR, file)}: ${items.length} item(s)`)
    }
  }

  const actions = allItems.filter(item => item.type === "action")
  const events = allItems.filter(item => item.type === "event")

  console.log(`\nExtracted ${actions.length} actions and ${events.length} events`)

  // Generate TypeScript in Contract/Generated for reference
  const tsContent = generateTypeScript(actions, events)
  const tsOutputPath = path.resolve(DEST_DIR, "ts", "ZylanceConstants.ts")
  fs.mkdirSync(path.dirname(tsOutputPath), { recursive: true })
  writeFileSync(tsOutputPath, tsContent, "utf-8")
  console.log(`\nGenerated TypeScript: ${path.relative(CONTRACT_DIR, tsOutputPath)}`)

  // Generate C#
  const csContent = generateCSharp(actions, events)
  const csOutputPath = path.resolve(DEST_DIR, "cs", "ZylanceConstants.cs")
  fs.mkdirSync(path.dirname(csOutputPath), { recursive: true })
  writeFileSync(csOutputPath, csContent, "utf-8")
  console.log(`Generated C#: ${path.relative(CONTRACT_DIR, csOutputPath)}`)

  console.log("\n✓ Successfully generated type-safe constants!")
}

/**
 * Find all .proto files in the api directory.
 */
async function findProtoFiles (): Promise<string[]> {
  const pattern = "zylance/api/**/*.proto"
  return await glob(pattern, {
    cwd: CONTRACT_DIR,
    absolute: true,
    windowsPathsNoEscape: true,
  })
}

/**
 * Parse a proto file and extract all action and event names.
 */
function parseProtoFile (filePath: string): ActionOrEvent[] {
  const content = readFileSync(filePath, "utf-8")
  const results: ActionOrEvent[] = []

  // Match option (action|eventName) = "value" lines
  const optionPattern = /option\s*\((action|eventName)\)\s*=\s*['"]([^'"]+)['"]/g

  let match: RegExpExecArray | null
  while ((match = optionPattern.exec(content)) !== null) {
    const [, optionType, value] = match
    results.push({
      name: value,
      type: optionType === "action" ? "action" : "event",
      file: path.relative(CONTRACT_DIR, filePath),
    })
  }

  return results
}

/**
 * Generate TypeScript constants file.
 */
function generateTypeScript (actions: ActionOrEvent[], events: ActionOrEvent[]): string {
  const allActions = [...new Set(actions.map(a => a.name))].sort()
  if (allActions.length === 0) throw new Error(`No action types found`)

  const allEvents = [...new Set(events.map(e => e.name))].sort()
  if (allEvents.length === 0) throw new Error(`No event types found`)

  const actionTypes = allActions.map(name => `| "${name}"`)
  const eventTypes = allEvents.map(name => `| "${name}"`)

  const actionConstants = allActions
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_")
      return `${safeName}: "${name}" as const`
    })

  const eventConstants = allEvents
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_")
      return `${safeName}: "${name}" as const`
    })

  //language=ts
  return trimLines(`
    /**
     * Auto-generated type-safe action and event name constants.
     * DO NOT EDIT - Generated by Scripts/Lib/generate-constants.ts
     */

    /**
     * All available request action names.
     */
    export type ZylanceAction =
      ${actionTypes.join("\n      ")};

    /**
     * All available event names.
     */
    export type ZylanceEvent =
      ${eventTypes.join("\n      ")};

    /**
     * Type-safe action name constants.
     */
    export const ZylanceActions = {
      ${actionConstants.join(",\n      ")},
    } as const

    /**
     * Type-safe event name constants.
     */
    export const ZylanceEvents = {
      ${eventConstants.join(",\n      ")},
    } as const
  `)
}

/**
 * Generate C# constants file.
 */
function generateCSharp (actions: ActionOrEvent[], events: ActionOrEvent[]): string {
  const allActions = [...new Set(actions.map(a => a.name))].sort()
  if (allActions.length === 0) throw new Error(`No action types found`)

  const allEvents = [...new Set(events.map(e => e.name))].sort()
  if (allEvents.length === 0) throw new Error(`No event types found`)

  const actionConstants = allActions
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_")
      return `public const string ${safeName} = "${name}";`
    })

  const eventConstants = allEvents
    .map(name => {
      const safeName = name.replace(/:/g, "_").replace(/\s+/g, "_")
      return `public const string ${safeName} = "${name}";`
    })

  //language=cs
  return trimLines(`
    // <auto-generated>
    //     This file is auto-generated by Scripts/generate-constants.ts
    //     DO NOT EDIT - Changes will be overwritten
    // </auto-generated>

    namespace Zylance.Contract;

    #pragma warning disable CS1591 // Disable missing XML comment warnings for auto-generated code

    /// <summary>
    /// All available request action names.
    /// </summary>
    public static class ZylanceActions
    {
        ${actionConstants.join("\n            ")}
    }

    /// <summary>
    /// All available event names.
    /// </summary>
    public static class ZylanceEvents
    {
        ${eventConstants.join("\n            ")}
    }

    #pragma warning restore CS1591
  `)
}

function trimLines (str: string): string {
  const lines = str.split("\n")

  // Remove leading empty line if present
  if (lines[0].trim() === "") lines.shift()

  const trimmedLines = lines.map(line => line.trimEnd())
  const indentLengths = trimmedLines
    .filter(line => line.trim().length > 0)
    .map(line => line.match(/^\s*/)?.[0].length ?? 0)

  const minIndent = Math.min(...indentLengths)
  const leadingIndentRegex = new RegExp(`^\\s{${minIndent}}`)

  return trimmedLines
    .map(line => line.replace(leadingIndentRegex, ""))
    .join("\n")
}

