<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
        <TargetPlatformIdentifier/>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.34.0-rc1"/>
        <PackageReference Include="Grpc.Tools" Version="2.76.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <PropertyGroup>
        <YarnExe Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(NODE_HOME)\yarn.cmd</YarnExe>
        <YarnExe Condition="!$([MSBuild]::IsOSPlatform('Windows'))">$(NODE_HOME)/bin/yarn</YarnExe>
        <TsOutputPath>../Zylance.UI/Generated</TsOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <!-- Track all proto files as inputs for incremental build -->
        <Protobuf Include="./zylance/**/*.proto" GrpcServices="None"/>
    </ItemGroup>

    <Target Name="GenerateTS"
            AfterTargets="Build"
            Inputs="@(Protobuf);$(MSBuildProjectFile)"
            Outputs="$(TsGeneratedMarker)/.generated">
        <Message Importance="high" Text="Generating TypeScript from Protocol Buffers..."/>
        <Exec Command="$(YarnExe) install"/>
        <Exec Command="$(YarnExe) build &quot;$(TsOutputPath)&quot;" EnvironmentVariables="NO_COLOR=1; NODE_DISABLE_COLORS=1"/>
        <Touch Files="$(TsOutputPath)/.generated" AlwaysCreate="true"/>
    </Target>
</Project>
